ALTER TABLE [dbo].[TimeEntries]
    ADD CONSTRAINT [PK_TimeEntries] PRIMARY KEY CLUSTERED ([TimeEntryId] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

