ALTER TABLE [dbo].[BillingTerms]
    ADD CONSTRAINT [PK_BillingTerms] PRIMARY KEY CLUSTERED ([BillingTermsId] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

